apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
     app: demo-voting-app
     namespace: vote
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app