apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: demo-voting-app
    name: result-service
    namespace: vote
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app